# docker-compose version
version: "3.8"

# Services
services:

    # first host
    client: 
        build: 
            context: . 
            dockerfile: client.Dockerfile 
        container_name: client 
        ports:
            - "6942:6942" 
        networks:
            - netUwUrk

    # second host
    server: 
        build: 
            context: . 
            dockerfile: server.Dockerfile 
        container_name: server 
        ports:
            - "4269:4269" 
        networks:
            - netUwUrk
    
networks:
    netUwUrk:
        driver: bridge
