# docker-compose version
version: "3.8"

# Services
services:

    
    client_tcp: 
        build: 
            context: . 
            dockerfile: Dockerfile 
        container_name: client 
        ports:
            - "6942:6942" 
        networks:
            - netUwUrk

    
    server_tcp: 
        build: 
            context: . 
            dockerfile: Dockerfile 
        container_name: server 
        ports:
            - "4269:4269" 
        networks:
            - netUwUrk

    client_udp: 
        build: 
            context: . 
            dockerfile: Dockerfile 
        container_name: client 
        ports:
            - "6942:6942" 
        networks:
            - netUwUrk

    
    server_udp: 
        build: 
            context: . 
            dockerfile: Dockerfile 
        container_name: server 
        ports:
            - "4269:4269" 
        networks:
            - netUwUrk
    
networks:
    netUwUrk:
        driver: bridge
